# Generated by Django 5.2.8 on 2025-11-21 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('file_id', models.CharField(max_length=255, unique=True)),
                ('file_unique_id', models.CharField(max_length=255, unique=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='bot_userima_user_id_ece338_idx')],
            },
        ),
    ]
