# Generated by Django 5.2.8 on 2025-11-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
