# Generated by Django 5.2.8 on 2025-11-26 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_telegramuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='bot.city'),
        ),
    ]
